site_name: "Manipulaci贸 de documents web: Javascript"

nav:
  - "Inici": 'index.md'
  - "1. Introducci贸": '1.intro.md'
  - "2. Generalitats de Javascript": '2.generalitats.md'
  - "3. Elements de llenguatge": '3.Elements.md'
  - "4. Funcions": '4.Funcions.md'
  - "5. Programaci贸 Estructurada": '5.PrgEstructurada.md'
  - "6. Programaci贸 Orientada a Objectes": '6.POO.md'
  - "Exercicis": "Exercicis.md"
  
theme:
  name: 'material'
  custom_dir: 'overrides'
  logo: 'img/logo.svg'
  favicon: 'img/logo.svg'
  features:
    - content.code.copy # PEr copiar codi
  palette:
    accent: deep purple
    primary: amber


extra_css:
  - https://joamuran.net/curs24_25/css/material-just.css

plugins:
  - search
  - glightbox   # Per vore les imatges en gran quan fas clic en elles.
  # - pandoc

markdown_extensions:
  - attr_list           # Permet incorporar atributs a les imatges { width=100px }
  - md_in_html # Junt a attr_list per afegir peus a les imatges
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      baselevel: 2
      toc_depth: 3