site_name: "U4. Validació i conversió de documents"

nav:
  - "Inici": 'index.md'
  - "Validació: DTD i XSD": '1.validacio.md'
  - "Conversió de documents": '2.conversio.md'
  - "Generació de documents PDF": '3.generaciopdf.md'
theme:
  name: 'material'
  custom_dir: 'overrides'
  logo: 'img/logo.svg'
  favicon: 'img/logo.svg'
  features:
    - content.code.copy # PEr copiar codi
  palette:
    accent: deep purple
    primary: amber


extra_css:
  - https://joamuran.net/curs24_25/css/material-just.css

plugins:
  - search
  - glightbox   # Per vore les imatges en gran quan fas clic en elles.
  # - pandoc

markdown_extensions:
  - attr_list           # Permet incorporar atributs a les imatges { width=100px }
  - md_in_html # Junt a attr_list per afegir peus a les imatges
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      baselevel: 2
      toc_depth: 3