site_name: "Web Components"

nav:
  - "Inici": 'index.md'
  - "1. Web Components": '1.intro.md'
  - "2. Encapsuladi贸 d'estils i plantilles": '2.estils.md'
  - "3. Comunicaci贸": '3.comunicacio.md'
  - "4. Components reactius": '4.reactivitatComponent.md'
  - "5. Composici贸": '5.composicio.md'
  - "6. El Just Eat Pizza": 
    - "6.1. Sprint 1": "sprint1.md"
    - "6.2. Sprint 2": "sprint2.md"
    - "6.3. Sprint 3": "sprint3.md"
  #  - "6.1. Sprint 1": "pizza_sprint_1"
  #- "4. Gesti贸 de formularis HTML amb JS": '4.forms.md'
  
theme:
  name: 'material'
  custom_dir: 'overrides'
  logo: 'img/logo.svg'
  favicon: 'img/logo.svg'
  features:
    - content.code.copy # PEr copiar codi
  palette:
    accent: deep purple
    primary: amber


extra_css:
  - https://joamuran.net/curs24_25/css/material-just.css

plugins:
  - search
  - glightbox   # Per vore les imatges en gran quan fas clic en elles.
  #- plantuml:
  #    puml_url: https://www.plantuml.com/plantuml/
  #    puml_keyword: plantuml # Per defecte puml
  - mkdocs_jarplantuml:
      plantuml_jar: /home/joamuran/devtools/plantuml-1.2025.0.jar
      output_format: svg
      output_dir: diagrames

markdown_extensions:
  - attr_list           # Permet incorporar atributs a les imatges { width=100px }
  - md_in_html # Junt a attr_list per afegir peus a les imatges
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      baselevel: 2
      toc_depth: 3
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
